# Generated by Django 5.0.7 on 2024-07-29 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2024, 7, 29)),
        ),
    ]
